#!/bin/bash

while getopts i: option
  do
  case "${option}" in
    i) ID=${OPTARG};;
  esac
done

curl  -H "Content-Type: application/json" --request POST 'localhost:4000/train' --data '{"id":"'"$ID"'"}'
